version: '3.9'
services:
  nats:
    image: nats
    ports:
      - '4222:4222'
    networks:
      - proxynet
    command: "-c /etc/nats/nats.conf"
    volumes:
      - ./nats-config/:/etc/nats
  # redis:
  #   image: redis:latest
  #   volumes:
  #     - './volumes/redis:/data'
  #   ports:
  #     - '6379:6379'
  #   command: ['redis-server', '--appendonly', 'yes']
  #   networks:
  #     - proxynet

  watcher:
    build: ./changeset-watcher
    depends_on:
      - nats
    environment:
      - NATS_IP=nats
    restart: unless-stopped
    networks:
      - proxynet

networks:
  proxynet:
    name: osm_cqrs_network