version: '3.9'
services:
  nats:
    image: nats
    ports:
      - '4222:4222'
    networks:
      - proxynet
    command: "-c /etc/nats/nats.conf"
    volumes:
       - ./nats-config/:/etc/nats

networks:
  proxynet:
    name: osm_cqrs_network