version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - proxynet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - proxynet

  search-backend:
    container_name: search-backend
    build: .
    environment:
      - PORT=6000
      - NATS_IP=nats
      - ES_IP=http://elasticsearch:9200
    networks:
      - proxynet

volumes:
  elasticsearch-data:
    driver: local

networks:
  proxynet:
    name: osm_cqrs_network
