version: "3.8"

services:
  renderer-postgis:
    image: kartoza/postgis:14-3.1
    volumes:
      - renderer-postgis-data:/var/lib/postgresql
    env_file: ./renderer/.env
    ports:
      - "25432:5432"
    restart: unless-stopped
    networks:
      - osm_proxy
    shm_size: 1g

  tegola:
    image: gospatial/tegola:edge
    volumes:
      - ./renderer/tegola:/opt/tegola_config
    command: [ 'serve', '--config', '/opt/tegola_config/config.toml' ]
    depends_on:
      - renderer-postgis
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - osm_proxy

  importer:
    build:
      context: ./renderer
    env_file: ./renderer/.env
    volumes:
      - renderer-importer-diff:/src/imposm/diff
      - renderer-importer-cache:/src/imposm/cache
      - ./renderer/data:/src/data
    depends_on:
      - postgis
    networks:
      - osm_proxy
    environment:
      - NATS_IP=${NATS_IP}

volumes:
  renderer-postgis-data:
  renderer-importer-diff:
  renderer-importer-cache:

networks:
  osm_proxy:
    name: osm_cqrs_network